import { Routes } from '@angular/router';

import { DashboardComponent } from '../../pages/dashboard/dashboard.component';
import { UserProfileComponent } from '../../pages/user-profile/user-profile.component';

import { NewsavingsaccountComponent } from '../../pages/savings/newsavingsaccount/newsavingsaccount.component';
import { AllsavingsaccountComponent } from '../../pages/savings/allsavingsaccount/allsavingsaccount.component';
import { OnesavingsaccountComponent } from '../../pages/savings/onesavingsaccount/onesavingsaccount.component';
import { AllcontributionsComponent } from '../../pages/contribution/allcontributions/allcontributions.component';
import { OnecontributionComponent } from '../../pages/contribution/onecontribution/onecontribution.component';
import { NewcontributionComponent } from '../../pages/contribution/newcontribution/newcontribution.component';
import { LoanAccountComponent } from '../../pages/loan/loan-account/loan-account.component';
import { LoanPaymentComponent } from '../../pages/loan/loan-payment/loan-payment.component';
import { NewLoanAccountComponent } from '../../pages/loan/new-loan-account/new-loan-account.component';
import { NewLoanPaymentComponent } from '../../pages/loan/new-loan-payment/new-loan-payment.component';
import { OneLoanPaymentComponent } from '../../pages/loan/one-loan-payment/one-loan-payment.component';
import { OneLoanAccountComponent } from '../../pages/loan/one-loan-account/one-loan-account.component';
import { OverdraftPaymentComponent } from '../../pages/overdraft/overdraft-payment/overdraft-payment.component';
import { OverdraftAccountComponent } from '../../pages/overdraft/overdraft-account/overdraft-account.component';
import { OneOverdraftAccountComponent } from '../../pages/overdraft/one-overdraft-account/one-overdraft-account.component';
import { NewOverdraftAccountComponent } from '../../pages/overdraft/new-overdraft-account/new-overdraft-account.component';
import { NewOverdraftPaymentComponent } from '../../pages/overdraft/new-overdraft-payment/new-overdraft-payment.component';
import { OneOverdraftPaymentComponent } from '../../pages/overdraft/one-overdraft-payment/one-overdraft-payment.component';
import { AuthGuard } from "../../services/auth-guard.service";
import { NewUserComponent } from 'src/app/pages/users/new-user/new-user.component';
import { UsersListComponent } from 'src/app/pages/users/users-list/users-list.component';

export const AdminLayoutRoutes: Routes = [
    { path: 'dashboard', component: DashboardComponent },
    { path: 'user-profile', component: UserProfileComponent },
    { path: 'users', component: UsersListComponent },
    { path: 'new-user', component: NewUserComponent },
    { path: 'savings-account', component: AllsavingsaccountComponent },
    { path: 'new-savings-account', component: NewsavingsaccountComponent },
    { path: 'edit-savings-account', component: OnesavingsaccountComponent },
    { path: 'contributions', component: AllcontributionsComponent },
    { path: 'new-contribution', component: NewcontributionComponent },
    { path: 'single-contribution', component: OnecontributionComponent },
    { path: 'loan-account', component: LoanAccountComponent },
    { path: 'loan-payment', component: LoanPaymentComponent },
    { path: 'new-loan-account', component: NewLoanAccountComponent },
    { path: 'new-loan-payment', component: NewLoanPaymentComponent },
    { path: 'one-loan-account', component: OneLoanAccountComponent },
    { path: 'one-loan-payment', component: OneLoanPaymentComponent },
    { path: 'overdraft-account', component: OverdraftAccountComponent },
    { path: 'overdraft-payment', component: OverdraftPaymentComponent },
    { path: 'new-overdraft-account', component: NewOverdraftAccountComponent },
    { path: 'new-overdraft-payment', component: NewOverdraftPaymentComponent },
    { path: 'one-overdraft-account', component: OneOverdraftAccountComponent },
    { path: 'one-overdraft-payment', component: OneOverdraftPaymentComponent },
];
